pipeline{
agent any
stages{
stage('Compilacion'){
    steps{
dir('calcSuma'){
    sh 'mvn clean package -DskipTests'
}
}
}
stage('Pruebas'){
    steps{
dir('calcSuma'){
    sh 'mvn test'
}
}
}
stage('Ejecutar:develop'){
    
when{
    branch 'develop'
}
steps{
dir('calcSuma'){
sh 'java -jar target/calcSuma-1.0-SNAPSHOT.jar 5 5
'
}
}
}
stage('Ejecutar:production'){
    
when{
    branch 'production'
}
steps{
dir('calcSuma'){
sh 'java -jar target/calcSuma-1.0-SNAPSHOT.jar 2 2
'
}
}
}
}
}
